### ISSUE TITLE
3D map is blank on Raspberry Pi 5 and Raspberry Pi OS

### ISSUE THREAD

**Issue by srs4511351** [f4exb/sdrangel#2246]
On a Raspberry Pi OS Bookworm system, 3D map works on a Raspberry Pi 4.
With the same image, booted on a Raspberry Pi 5 the 3D map is blank.

On a Raspberry Pi OS built by Raspberry Pi for a RPI 5, and with SDRangel installed on the RPI 5, the 3D map is blank.
With Ubuntu 24.04, on a Raspberry Pi 5, the 3D map works.

This is strikingly similar to a problem with GridTracker. On the RPI 5, it only works on OSes that are not Raspberry Pi OS or DietPI.

Does SDRangel 3D maps use NWJS? Here is some insight into the GridTracker issue.
https://groups.io/g/GridTrackerApp/topic/instructions_to_build_from/103035128
"GT itself is a NWJS application, so its essentially a web app that is mostly html and JavaScript. As such there isn't much to compile and what segfaults is the nwjs execution environment."

I attached the log file from running SDRangel with maps open, then I quit. I have the 3D models downloaded.
[sdrangel.log](https://github.com/user-attachments/files/16902081/sdrangel.log)

**Comment by srcejon** [comment]
The 3D Map uses Cesium. 

Does this work for you? https://sandcastle.cesium.com/

**Comment by srs4511351** [comment]
Yes, it does work in Firefox on my Raspberry Pi.

My Windows computer does not work in Google Chrome and Firefox. It suggests that I don't have WebGL

**Comment by srcejon** [comment]
> Yes, it does work in Firefox on my Raspberry Pi.

Which one? 5 with Pi OS?

**Comment by srs4511351** [comment]
It worked on both the RPI 5 with Dietpi OS and Raspberry Pi OS on the RPI 5. 3D maps are also blank in Dietpi.

**Comment by srs4511351** [comment]
Sorry, my previous reply was confusing.
3D maps work on RPI 4.
3D maps do not work and are blank on RPI 5 Raspberry Pi OS, and Dietpi
They do work on Ubuntu.

**Comment by srs4511351** [comment]
Is there any progress getting 3D maps working on the Raspberry Pi 5 running Raspberry Pi OS?

**Comment by srcejon** [comment]
Nope - I don't have one to try. From your description, sounds like it's probably not an SDRangel specific problem anyway.

**Comment by srs4511351** [comment]
Thanks for the update.
It does work on https://sandcastle.cesium.com/

**Comment by srcejon** [comment]
The version of cesium we are using is a couple of years old, so I'll try updating it

**Comment by srs4511351** [comment]
Thank you.

**Comment by srs4511351** [comment]
Please update version of cesium.
The issue is expiring...

Thanks, Steve

**Comment by srs4511351** [comment]
Please update version of cesium.
The issue is expiring...

Thanks, Steve

**Comment by srcejon** [comment]
New version of Cesium included in 7.22.8.

**Comment by srs4511351** [comment]
I rebuilt SDRangel with version 7.22.8.
3D maps are still blank.

**Comment by srs4511351** [comment]
I installed DietPi Trixie and a new install of SDRangel on my RPI5.
The 3D maps now displays an error message.

Error constructing CesiumWidget.
It has a link to http://get.webgl.org/ to verify my browser's WebGl support. My browser does support WebGl.

Detailed information was displayed:
```
RuntimeError: The browser supports WebGL, but initialization failed.
Error
    at new QL (http://127.0.0.1:36517/Cesium/Cesium.js:75:138)
    at xXe (http://127.0.0.1:36517/Cesium/Cesium.js:1770:59447)
    at new Cu (http://127.0.0.1:36517/Cesium/Cesium.js:1770:53861)
    at new li (http://127.0.0.1:36517/Cesium/Cesium.js:10710:1139)
    at new Go (http://127.0.0.1:36517/Cesium/Cesium.js:10806:8459)
    at new qi (http://127.0.0.1:36517/Cesium/Cesium.js:10983:13503)
    at http://127.0.0.1:36517/map/map/map3d.html:237:24
```
I hope this helps.

**Comment by srcejon** [comment]
Currently 3D map isn't working due to Quota being exceeded. You'd need to add your own API key as described here: https://github.com/f4exb/sdrangel/issues/2446

Not sure if that is causing the problem you are reporting, however.
