### ISSUE TITLE
DragonOS feature map CesiumWidget issue

### ISSUE THREAD

**Issue by KhanTheDaleK1** [f4exb/sdrangel#2290]
----------------------------------
Message: 

Error constructing CesiumWidget.
Visit http://get.webgl.org to verify that your web browser and hardware support WebGL. Consider trying a different web browser or updating your video drivers. Detailed error information is below:

Visit http://get.webglorg to verify that your web browser and hardware support WebGL. Consider trying a RuntimeError: The browser supports WebGL, but initialization failed.
at new RuntimeError (http://127.0.0.1:43539/Cesium/Cesium.js: 1:42568) at new Context (http://127.0.0.1:43539/Cesium/Cesium.js:50:2285107) at new Scene (http://127.0.0.1:43539/Cesium/Cesium.js:50:2978056) at new CesiumWidget (http://127.0.0.1:43539/Cesium/Cesium.js:90:151578) at new Viewer (http://127.0.0.1:43539/Cesium/Cesium.js:90:242895) at http://127.0.0.1:43539/map/map/map3d.html:217:20

----------------------------------

**Comment by srcejon** [comment]
Does this page work for you? https://sandcastle.cesium.com/?src=3D%20Models.html (You should see a 3d model of a plane)
